# You can find the english version example file in GitHub or spigotmc.org

# 该条目的唯一识别id，请勿重复
example:
  # 类别，若不填则默认default
  category: default
  # 未解锁时是否在ui中显示
  show: true
  # 在ui中的图标，必须存在，否则会报错
  icon:
    name: "&6example"
    material: WOODEN_SWORD
    custom-model-data: 10001
    shiny: true
    lore:
      - "&7This is an example item."
  # 若不存在则默认已解锁
  unlock:
    # 可选的解锁类型有: item/event/both/none
    # item - 拾起物品解锁
    # event - 触发对应事件解锁
    # both - 两者同时达成解锁
    # none - 不需要解锁
    type: item
    item:
      name: "example" # 带有该名字的物品获取后解锁
      # 带有该lore的物品获取后解锁
      lore:
      - "example"
      consume: false # 是否消耗物品
    event:
      # 内置的事件类型有:
      # player-join: 玩家加入事件
      # player-quit: 玩家离开事件
      # entity-kill: 实体死亡事件(击杀怪物事件)
      # waystone-active: 激活传送石事件
      # craft-item: 合成物品事件
      # interact-item: 交互物品事件
      type: "entity-kill" # 触发的事件类型
      # 当type为entity-kill时，该字段才有效
      entity-info:
        name: "exampleMob" # 当名字中包含该字符串时触发，忽略颜色符号
        amount: 10 # 当击杀够该数量的生物时触发，不填则默认1，若为0也认为是1
      # 当type为waystone-active时，该字段才有效
      waystone-name: "exampleWaystone" # 传送石名称
      # 当type为craft-item/interact-item时，该字段才有效
      item:
        name: "example"
        lore:
          - "example"
        consume: false # 是否消耗物品
  # 解锁后触发的奖励
  reward:
    # kether语句，可以在 https://kether.tabooproject.org/list.html 查看kether语句大全
    content: |-
      command inline "give {{ sender }} diamond 1" as op
      tell color inline "&a你解锁了一个名叫 {{ &entry }} &a的条目!"
    compat:
      # mmocore兼容的奖励
      mmocore:
        enable: true # 是否启用
        attribute: "strength" # 属性名，不填默认strength
        amount: 1 # 属性值，不填默认1
      mythiclib:
        enable: true # 是否启用
        attribute: "damage" # 属性名，不填默认damage
        amount: 1 # 属性值，不填默认1