title: "Illustration | Default Category"
# unique id of the category
category: "default"

# abstract character layout
# @ always represents the icon of the illustration category
# the rows of the layout represent the rows of the gui, and the maximum cannot exceed 6 rows
layout:
  - "####SB###"
  - "#@@@@@@@#"
  - "#@@@@@@@#"
  - "#@@@@@@@#"
  - "P@@@@@@@N"
  - "####M####"

# all icon can be fully customized
icon:
  # unique character of the icon
  # !!!must be one character!!!
  '#':
    type: normal # the type of the icon, optional values are: normal/main/next/previous
    material: BLACK_STAINED_GLASS_PANE
    name: ' '
  S:
    material: SKULL
    name: '{player_name}'
    lore:
      - '&aPersonal Information'
  B:
    material: NAME_TAG
    name: 'Unlocked Progress'
    lore:
      - '{{ bar default }} &a{{ unlocked default }}&f/&a{{ count default }}'
  N:
    type: next
    material: ARROW
    name: 'Next page'
  P:
    type: previous
    material: ARROW
    name: 'Previous page'
  M:
    type: main
    material: ARROW
    name: 'Back to main'